const {catchAsync, catchWithCustomError} = require('./catchAsync');


module.exports = { catchAsync ,catchWithCustomError };
